<a href="https://colab.research.google.com/github/vigneshd5750/CLV/blob/master/numpyexr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [8]:
np.full(10,5)


array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [9]:
np.full(10,1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [16]:
even=np.arange(10,51)
even


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [19]:
even[::2]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [21]:
mat = np.arange(0,9)
mat

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
mat.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
q= np.random.random(1)
q


array([0.77356447])

In [65]:
i= np.random.normal(0,26,25)
i


array([  8.19855859,   3.80783098,  25.6906202 ,   2.14315214,
        11.91750697,  99.2713727 ,  -3.79370622, -35.36632441,
        47.70525449,  -2.96022847,  36.03366526,  -6.17266537,
       -21.48923676,  15.31088501,  -1.91500904, -20.11098903,
        23.15212297,  20.45499378,  10.03276998,  41.03126537,
        -8.36683242,  18.30778667, -12.24026088,   0.53218942,
        -9.21507033])

In [90]:
vv= np.arange(0.01,1.01,0.01)
vv
vv.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [91]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [105]:
 mat= np.arange(1,26).reshape(5,5)
 mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [0]:
seq = mat

In [128]:
seq[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [129]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [130]:
seq

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [133]:
seq[3,4]

20

In [138]:
seq[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [139]:
seq[4:,:]

array([[21, 22, 23, 24, 25]])

In [140]:
seq[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [141]:
np.sum(seq)

325

In [142]:
np.std(seq)

7.211102550927978

In [145]:
np.sum(seq,axis=0)

array([55, 60, 65, 70, 75])